export const auth = {
  login: {
    title:      'Accedi',
    subtitle:   'Accedi al tuo account',
    email:      'Email',
    password:   'Password',
    submit:     'Accedi',
    loading:    'Accesso in corso...',
    divider:    'oppure',
    noAccount:  'Non hai un account?',
    signUp:     'Registrati',
    google:     'Accedi con Google',
    error:      'Email o password non validi',
    genericError: 'Accesso fallito',
  },
  register: {
    title:             'Registrati',
    subtitle:          'Crea il tuo account',
    email:             'Email',
    password:          'Password',
    confirmPassword:   'Conferma password',
    helperText:        'Almeno 8 caratteri',
    submit:            'Crea account',
    loading:           'Creazione account...',
    hasAccount:        'Hai già un account?',
    signIn:            'Accedi',
    passwordMismatch:  'Le password non corrispondono',
    passwordTooShort:  'La password deve contenere almeno 8 caratteri',
    genericError:      'Registrazione fallita',
  },
  oauth: {
    processing: 'Completando accesso...',
  },
} as const;