export const shared = {
  actions: {
    cancel:    'Annulla',
    save:      'Salva',
    delete:    'Elimina',
    remove:    'Rimuovi',
    confirm:   'Conferma',
    retry:     'Riprova',
    download:  'Scarica',
    promote:   'Promuovi ad asset',
    rename:    'Rinomina',
    viewAsset: 'Vedi asset',
    close:     'Chiudi',
    send:      'Invia',
    invite:    'Invita',
    back:      'Indietro',
    logout:    'Logout',
  },
  status: {
    loading:          'Caricamento...',
    error:            'Si è verificato un errore',
    empty:            'Nessun elemento',
    success:          'Operazione completata',
    cancelled:        'Operazione annullata',
    selectWorkspace:  'Seleziona un workspace',
    noWorkspace:      'Nessun workspace disponibile',
    soon:             'presto',
  },
  sessionStatus: {
    queued:    'In coda',
    running:   'In esecuzione',
    completed: 'Completata',
    failed:    'Fallita',
    cancelled: 'Annullata',
    draft:     'Bozza',
    step:      'step',
    steps:     'steps',
  },
  format: {
    date:     'DD/MM/YYYY',
    datetime: 'DD/MM/YYYY HH:mm',
  },
  form: {
    email: 'Email',
    role:  'Ruolo',
  },
  roles: {
    editor: 'Editor',
    viewer: 'Viewer',
  },
  aria: {
    openMenu:          'Apri menu',
    closeMenu:         'Chiudi menu',
    userMenu:          'Menu utente',
    toggleTheme:       'Cambia tema',
    mainNavigation:    'Navigazione principale',
    expandSidebar:     'Espandi sidebar',
    collapseSidebar:   'Comprimi sidebar',
    removeMember:      'Rimuovi membro',
    sendMessage:       'Invia messaggio',
  },
  wcag: {
    skipToContent: 'Vai al contenuto',
  },
  label: {
    tools:    'Tools',
    theme:    'Tema',
    soon:     'presto',
    deleteWorkspaceWarning: 'L\'eliminazione di "{name}" rimuoverà tutti gli asset, sessioni e conversazioni. Questa azione non può essere annullata.',
  },
  chat: {
    failedToSend:       'Impossibile inviare il messaggio',
    typingReply:        'Risposta in arrivo...',
    typeYourMessage:    'Scrivi il tuo messaggio...',
  },
} as const;