export const shared = {
  brand: {
    appName:   'flow app',
  },
  actions: {
    cancel:     'Annulla',
    cancelling: 'Annullamento...',
    save:       'Salva',
    delete:    'Elimina',
    remove:    'Rimuovi',
    confirm:   'Conferma',
    retry:     'Riprova',
    download:  'Scarica',
    promote:   'Promuovi ad asset',
    rename:    'Rinomina',
    viewAsset: 'Vedi asset',
    close:     'Chiudi',
    send:      'Invia',
    invite:    'Invita',
    back:      'Indietro',
    logout:    'Logout',
  },
  status: {
    loading:          'Caricamento...',
    error:            'Si è verificato un errore',
    empty:            'Nessun elemento',
    success:          'Operazione completata',
    cancelled:        'Operazione annullata',
    selectWorkspace:  'Seleziona un workspace',
    noWorkspace:      'Nessun workspace disponibile',
    soon:             'presto',
  },
  sessionStatus: {
    queued:    'In coda',
    running:   'In esecuzione',
    completed: 'Completata',
    failed:    'Fallita',
    cancelled: 'Annullata',
    draft:     'Bozza',
    step:      'step',
    steps:     'steps',
  },
  format: {
    date:     'DD/MM/YYYY',
    datetime: 'DD/MM/YYYY HH:mm',
  },
  form: {
    email: 'Email',
    role:  'Ruolo',
  },
  roles: {
    editor: 'Editor',
    viewer: 'Viewer',
  },
  aria: {
    openMenu:          'Apri menu',
    closeMenu:         'Chiudi menu',
    userMenu:          'Menu utente',
    toggleTheme:       'Cambia tema',
    mainNavigation:    'Navigazione principale',
    expandSidebar:     'Espandi sidebar',
    collapseSidebar:   'Comprimi sidebar',
    removeMember:      'Rimuovi membro',
    sendMessage:       'Invia messaggio',
    sessionDetail:     'Dettaglio sessione: {tool}',
    runningProgress:   'Progresso: {current} di {total}',
    completedStatus:   'Sessione completata',
    failedStatus:      'Sessione fallita',
    queuedStatus:      'Sessione in coda',
  },
  errorBoundary: {
    title:     'Something went wrong',
    retry:     'Try again',
  },
  wcag: {
    skipToContent: 'Vai al contenuto',
  },
  label: {
    tools:    'Tools',
    theme:    'Tema',
    soon:     'presto',
    deleteWorkspaceWarning: 'L\'eliminazione di "{name}" rimuoverà tutti gli asset, sessioni e conversazioni. Questa azione non può essere annullata.',
    session:  'Sessione',
    sessionWithTool: 'Sessione: {toolName}',
    status:   'Stato',
    steps:    'Step:',
    created:  'Creato:',
  },
  chat: {
    failedToSend:       'Impossibile inviare il messaggio',
    typingReply:        'Risposta in arrivo...',
    typeYourMessage:    'Scrivi il tuo messaggio...',
  },
  session: {
    interruptedMessage: 'Questa sessione è stata interrotta. Puoi riprovare avviando una nuova generazione dalla pagina ',
    queuedMessage:      'Generazione in elaborazione. Segui l\'avanzamento in questa pagina.',
    failedAtStep:       ' · Step {step}',
    queuePosition:      'Posizione in coda: {position}',
    newGeneration:      'Nuova generazione',
    xpEarned:           '+{xp} XP',
  },
} as const;