export const toolPage = {
  cta: {
    submit:     'Genera',
    submitting: 'Avvio in corso...',
    cancel:     'Annulla generazione',
    download:   'Scarica risultato',
    new:        'Nuova generazione',
  },
  readiness: {
    title:           'Pronto per generare?',
    allReady:        'Tutti i campi pronti',
    allSet:          'Tutti i requisiti soddisfatti. Pronto per generare.',
    missingFile:     'Carica un file',
    missingText:     'Inserisci un valore',
    missingAsset:    'Seleziona un asset o creane uno',
    noInputsRequired:'Nessun input richiesto. Puoi avviare la generazione direttamente.',
    statusOk:        'Configurato',
    statusMissing:   'Richiesto — mancante',
    statusOptional:  'Opzionale',
  },
  progress: {
    title:            'Avanzamento',
    stepLabel:        'Step {current} di {total}',
    stepCount:        '{count} step',
    stepCountSummary: '{count} step',
    creditCostSummary:'{count} crediti',
    artifactLabel:    'Step {number}',
    starting:         'Preparazione in corso...',
    completed:        'Generazione completata',
    completedIn:      'Completato in {duration}',
    failed:           'Generazione fallita',
    cancelled:        'Generazione annullata',
    reconnecting:     'Riconnessione in corso...',
  },
  feedback: {
    sessionStarted:   'Generazione avviata',
    stepCompleted:    '"{label}" completato',
    sessionCompleted: 'Risultato pronto',
    sessionFailed:    'Errore durante "{label}"',
  },
  download: {
    formatMd:       'Markdown',
    formatDocx:     'Word',
    formatPdf:      'PDF',
    formatTxt:      'Testo',
    formatLabel:    '{format} (.{ext})',
    formatDisabled: '{format} (.{ext}) — in arrivo',
  },
  config: {
    title:            'Configurazione',
    topic:            'Argomento',
    topicPlaceholder: 'Inserisci l\'argomento del contenuto',
    language:         'Lingua',
    startCta:         'Avvia generazione',
    fileUploadHint:   'Clicca per caricare o trascina il file',
    acceptedFormats:  'Formati accettati: {formats}',
    maxFileSize:      '(max {size}MB)',
    creditCost:       '{count} crediti',
  },
  assets: {
    emptyState:       'Nessun asset di tipo "{type}" disponibile. Creane uno dal workspace.',
    selectOne:        'Seleziona un asset',
    selectMultiple:   'Seleziona uno o più asset',
  },
} as const;