export const workspace = {
  list: {
    title:       'I tuoi workspace',
    empty:       'Nessun workspace. Creane uno per iniziare.',
    createCta:   'Nuovo workspace',
    createLabel: 'Nome workspace',
  },
  detail: {
    members:      '{count} members',
    deleteTitle:  'Elimina workspace',
    assets:       'Asset',
    recentSessions: 'Sessioni recenti',
    noSessions:   'Nessuna sessione. Avvia un tool per iniziare.',
    noAssets:     'Nessun asset. Genera un brief o una brand voice.',
    inviteMember: 'Invita membro',
  },
  nav: {
    home:            'Home',
    tools:           'Tools',
    sessions:        'Sessioni',
    assets:          'Asset',
    team:            'Team',
    templates:       'Templates',
    audit:           'Audit Log',
    newGeneration:   'Nuova Generazione',
    backToWorkspace: 'Torna al workspace',
  },
  switcher: {
    selectWorkspace: 'Seleziona un workspace',
    noWorkspaces: 'Nessun workspace',
  },
  assets: {
    renameTitle: 'Rinomina asset',
    renameLabel: 'Nome',
    defaultName: '{type}',
  },
  dashboard: {
    title: 'Dashboard',
    tools: 'Strumenti',
    recentSessions: 'Sessioni recenti',
    noSessions: 'Nessuna sessione ancora. Seleziona un tool per iniziare.',
    subtitle: 'Seleziona un tool per iniziare a generare contenuti',
    readyToPromote: 'Pronti da Promuovere',
    promoteHint: 'Promuovi ad Asset per renderlo disponibile come contesto',
    editAction: 'Modifica',
  },
  sessions: {
    tabs: {
      inProgress: 'In corso',
      completed: 'Completate',
      failed: 'Fallite',
    },
    emptyInProgress: 'Nessuna sessione in corso',
    emptyCompleted:  'Nessuna sessione completata',
    emptyFailed:     'Nessuna sessione fallita',
  },
  form: {
    createTitle: 'Nuovo Workspace',
    editTitle: 'Modifica Workspace',
    accentLabel: 'Colore accento',
  },
} as const;