name: Deploy

on:
  push:
    branches: [main, staging, dev]
    paths-ignore:
      - 'Wiki/**'
      - '**.md'
      - '.obsidian/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: read

concurrency:
  group: checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/_ci-checks.yml